modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "liosmultiloaderutils"
version = "${version}"
displayName = "Lio's Multiloader Utils"
authors = "Zigy,Liopyu"
description = '''
Lio's Fork of Zigy's Multiloader Utils
'''
#logoFile = ""

[[dependencies.liosmultiloaderutils]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.liosmultiloaderutils]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"